### ISSUE TITLE
environment.yml

### ISSUE THREAD

**Issue by catherine-qian** [nikhilsinghmus/room2reverb#24]
Dear authors,

Could you please kindly provide the environment.yml?

**Comment by nikhilsinghmus** [comment]
Hi, we didn’t use conda or another virtual environment for this project. We’ve listed the general dependencies in the ReadMe, but let me know if you run into issues with particular versions of them.

**Comment by catherine-qian** [comment]
Thanks for the reply.

BTW, for the depth encoder. did you use 'https://storage.googleapis.com/niantic-lon-static/research/monodepth2/mono_640x192.zip' this model （the first one listed in the attached table)?

**Comment by nikhilsinghmus** [comment]
Yes, that should be the one!

**Comment by catherine-qian** [comment]
thanks
