### ISSUE TITLE
about T60 metric

### ISSUE THREAD

**Issue by catherine-qian** [nikhilsinghmus/room2reverb#25]
Dear authors,'

Thanks for this awesome work!
1. Could you please let me know how you compute the T60 mean, and std in Table 3?
     Does it correspond to the 'test.py' script and take 1957 errors in %=(estimate-real)/real), and directly compute the mean and std? 
2. I guess the pretrained model corresponds to the checkpoint under `resources',  however, when I compute the T60 metric in point 1, it replies mean=60， std=253, which is different from the paper? 

Thanks for your help!

**Comment by nikhilsinghmus** [comment]
Hi, thank you for the question and kind words!

The final T60 script appears to be missing, my apologies for that (it should be eval_t603.py under scripts/, which produces Fig. 8). I'll work on tracking this down.

Re: numbers, those definitely feel quite off. although some amount of variation is expected (given the noise vector). I ran a quick version now with the checkpoint and got a mean of ~2% with SD ~66%.

Code for what I just ran is [here](https://web.media.mit.edu/~nsingh1/files/eval_t603.py), quickly recreated from memory, to run after test.py.

**Comment by catherine-qian** [comment]
> 
Thanks for your quick reply!

The test.py also compute the error statistics with the resulting files t60_err.npy, t60.json, t60.png while t60.png corresponds to  Fig. 8? Besides, the results saved in ` t60_err.npy' are different from the latestly provided eval_t603.py，even give the same audio RIR samples?

I run the test.py for 3 times to generate the dereverant audio samples, the resulting statistics from  eval_t603.py are as follows:
mean=-0.00048, variance=0.413 
mean=-0.01355, variance=0.402 
mean=-0.01444, variance=0.403
I guess the variations are because of the random noise. And the number reported in paper should *100 ( in %)?

**Comment by nikhilsinghmus** [comment]
Hi, yes; you can ignore the ones in the output directory (sorry about that, those were from an initial attempt to take a batched approach; I will work on cleaning the code up to avoid that), and multiply the other means by 100 to get the numbers reported in the paper. Std should be sqrt(var) * 100.

**Comment by catherine-qian** [comment]
thanks for your help!
