### ISSUE TITLE
repeated IRs

### ISSUE THREAD

**Issue by catherine-qian** [nikhilsinghmus/room2reverb#28]
Dear authors,

For the dataset description, you said 
"We curated a dataset of 265 different spaces totalling 1169 images and 738 IRs. From these, we produced a total of 11234 paired examples with a train- validation-test split of 9743-154-1957."

So, for the 11234 paired examples, did you duplicate the IRs i.e., some IRs in the provided dataset are exactly the same? And how do you choose which IR to duplicate?

**Comment by nikhilsinghmus** [comment]
Hi! All within-scene image-IR pairs were considered (pairwise). So if a given scene has 2 images and 2 IRs, we will have 4 pairs (and correspondingly, 2 copies of each IR, i.e. 1 for each image).

**Comment by catherine-qian** [comment]
thanks for the reply.
So that means there are both repeated IRs and images?
However, when I check the data.
I only found exactly the same IRs. For images, there exists little difference. Did you augment images (i.e., through crop) to make them different?

**Comment by nikhilsinghmus** [comment]
Hi, yes it’s possible that the crop was slightly randomized already for the images.
