### ISSUE TITLE
Request for Access to Dataset

### ISSUE THREAD

**Issue by inmoyeon** [nikhilsinghmus/room2reverb#34]
Dear authors of Image2Reverb,

Hi @nikhilsinghmus ,

As I am looking to expand on your remarkable work, I would greatly appreciate access to your curated dataset mentioned in the paper: "We curated a dataset of 265 different spaces totaling 1169 images and 738 IRs. From these, we produced a total of 11234 paired examples with a train-validation-test split of 9743-154-1957." 
I believe that having access to this dataset will significantly contribute to my research and enable me to build upon the foundation you have established.

I kindly request your permission to access the dataset. I assure you that the dataset will be used for academic and research purposes. If possible, please send me the dataset via email to "iyeon@kaist.ac.kr".

Thank you for your consideration.

**Comment by nikhilsinghmus** [comment]
Hi @iyeon915, just sent the data to you! All the best with your research, and thank you for your interest!

**Comment by inmoyeon** [comment]
Hi @nikhilsinghmus ,
Thank you for the quick reply and dataset!
